line-length = 120
target-version = "py313"

[format]
docstring-code-format = true
docstring-code-line-length = 80
quote-style = "double"
line-ending = "lf"
skip-magic-trailing-comma = true

[lint]
# https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "D", # Docstrings
    # "S101",    # Use of assert detected (we use it for typing and testing purposes)
    "COM812",  # Missing trailing comma (interferes with the formatter)
    # "TRY003",  # Avoid specifying long messages outside the exception class (has false positives)
    # "D105",    # Missing docstring in magic method
    # "SLOT000", # Subclasses of X should define `__slots__` (too many false positives, we use slotscheck instead)
    # "PLR2004", # Usage of "magic value" (consider removing in the future)
    # "SIM105",  # Use `contextlib.suppress` (worst for performance)
    # "SIM110",  # Use `any`/`all` (worst for performance)
    "TD002",   # Missing issue link for todo
    "TD003",   # Line contains todo
    "FIX002",  # Line contains todo
    "FBT003",  # Boolean positional argument in function call (more false positives than real ones)
    "EM101",   # Exceptions  must not use a string literal (unnecesarry complexity)
    "EM102",   # Exceptions  must not use a f-string literal (unnecesarry complexity)
    "TRY003",  # Avoid specifying long messages outside the exception class (unnecesarry complexity)
    "S104",    # Possible binding to all interfaces
    "ERA001",  # Found commented-out code
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]

[lint.per-file-ignores]
"**/__init__.py" = [
    "F403", # `from .events import *` used; unable to detect undefined names
]
"noxfile.py" = [
    "S101" # Use of assert detected
]
"backend/main.py" = [
    "PLW0603" #  Using the global statement to update `queries` is discouraged
]
"backend/db/*.py" = [
    "ALL"
]
"backend/utils/tokens.py" = [
    "S105"
]
"shared/internal/hooks.py" = [
    "ANN401"
]
"frontend/net/error.py" = [
    "PLR2004"
]
"frontend/old_main.py" = [
    "ALL"
]


[lint.isort]
required-imports = ["from __future__ import annotations"]
force-single-line = true

[lint.pydocstyle]
convention = "numpy"

[lint.pylint]
max-args = 20

[lint.mccabe]
max-complexity = 20