# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
#   sqlc-gen-better-python v0.4.4
"""Module containing models."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("User",)

import msgspec
import typing

if typing.TYPE_CHECKING:
    from shared.internal import Snowflake
    import collections.abc


class User(msgspec.Struct):
    """Model representing User.

    Attributes:
        id: Snowflake
        username: str
        password: str
        money: int
    """

    id: Snowflake
    username: str
    password: str
    money: int
