# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
#   sqlc-gen-better-python v0.4.4
"""Module containing queries from file queries.sql."""

from __future__ import annotations

__all__: collections.abc.Sequence[str] = ("Queries",)

from shared.internal import Snowflake
import typing

if typing.TYPE_CHECKING:
    import aiosqlite
    import collections.abc

from backend.db import models


GET_USER_BY_ID: typing.Final[str] = """-- name: GetUserById :one
SELECT id, username, password, money FROM users WHERE users.id = ?
"""


class Queries:
    """Queries from file queries.sql."""

    __slots__ = ("_conn",)

    def __init__(self, conn: aiosqlite.Connection) -> None:
        """Initialize the instance using the connection.

        Args:
            conn:
                Connection object of type `aiosqlite.Connection` used to execute the query.
        """
        self._conn = conn

    @property
    def conn(self) -> aiosqlite.Connection:
        """Connection object used to make queries.

        Returns:
            Connection object of type `aiosqlite.Connection` used to make queries.
        """
        return self._conn

    async def get_user_by_id(self, *, id_: Snowflake) -> models.User | None:
        """Fetch one from the db using the SQL query with `name: GetUserById :one`.

        ```sql
        SELECT id, username, password, money FROM users WHERE users.id = ?
        ```

        Args:
            id_: Snowflake.

        Returns:
            Result of type `models.User` fetched from the db. Will be `None` if not found.
        """
        row = await (await self._conn.execute(GET_USER_BY_ID, (int(id_),))).fetchone()
        if row is None:
            return None
        return models.User(id=Snowflake(row[0]), username=row[1], password=row[2], money=row[3])
